// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRGWzL0RbMV_FirabnGc35g-L4Htz417s',
    appId: '1:521005117441:web:aa6f8e11acadf761161000',
    messagingSenderId: '521005117441',
    projectId: 'pokemon-api-test-c9367',
    authDomain: 'pokemon-api-test-c9367.firebaseapp.com',
    storageBucket: 'pokemon-api-test-c9367.appspot.com',
    measurementId: 'G-93XD3FYEQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxC8Hb_l8-WBbudeCI1lYfP2G6wO8sKU',
    appId: '1:521005117441:android:56c6b5ec1d368e38161000',
    messagingSenderId: '521005117441',
    projectId: 'pokemon-api-test-c9367',
    storageBucket: 'pokemon-api-test-c9367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxGzbTkHNu3YhY5uu-QUCAcAkRLiNYd20',
    appId: '1:521005117441:ios:726b24c2dbdd5c00161000',
    messagingSenderId: '521005117441',
    projectId: 'pokemon-api-test-c9367',
    storageBucket: 'pokemon-api-test-c9367.appspot.com',
    iosBundleId: 'com.example.testingModel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxGzbTkHNu3YhY5uu-QUCAcAkRLiNYd20',
    appId: '1:521005117441:ios:1e33e4f82c2fef73161000',
    messagingSenderId: '521005117441',
    projectId: 'pokemon-api-test-c9367',
    storageBucket: 'pokemon-api-test-c9367.appspot.com',
    iosBundleId: 'com.example.testingModel.RunnerTests',
  );
}
